### ISSUE TITLE
vale uses SCons

### ISSUE THREAD

**Issue by andreas23** [project-everest/everest#26]
Yes, this is a major, major issue for me. In fact, it is blocking me from building vale at the moment.

Let me tell you a story of pain and suffering. It all starts out, as you are probably aware, with the fact that SCons works with the standalone Windows build of Python 2.7 only. Not with any cygwin version, not with any Python 3 version. Nothing that a little fiddling with the path wouldn't fix, of course, but already a showstopper for less weathered people.

Then, when actually trying to build vale, I get this nice and helpful warning:

scons: warning: you do not seem to have the pywin32 extensions installed;
        parallel (-j) builds may not work reliably with open Python files.

And shortly after, it promptly trips all over its feet:

scons: *** [obj\arch\x86\def.s.tmp] C:\Users\bogk\everest\vale\obj\arch\x86\def.s.tmp: The process cannot access the file because it is being used by another process

Yeah. At least you told me before that this would not be reliable.

I proceeded to try and install pywin32, as suggested. Found it on sourceforge, the installer fails however to detect my Python installation, and helpfully also refuses to allow me to manually specify one.

So I pull the source, to build from there. A few minor obstacles, like "where the heck is mc.exe living" and "chmod a+rx swig/swig.exe" (why precisely is this even living in a source archive?) are easily overcome. Then, a call to nmake fails:

c:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\nmake.exe /nologo /f makefile_pythonwin SUB_DIR_O=C:\Users\bogk\Downloads\pywin32-220\build\temp.win32-2.7\Release\scintilla SUB_DIR_BIN=C:\Users\bogk\Downloads\pywin32-220\build\temp.win32-2.7\Release\scintilla DIR_PYTHON=C:\Python27

Microsoft (R) Program Maintenance Utility Version 9.00.30729.01
Copyright (C) Microsoft Corporation.  All rights reserved.

NMAKE : fatal error U1065: invalid option '-'
Stop.
error: command 'nmake.exe' failed with exit status 2

And for the love of all that is holy, I can't find where that damn '-' is coming from.

So, please please please stop using SCons. It's an unmaintained piece of software depending on more unmaintained pieces of software. It's a major roadblock in getting people involved in your software, let alone actual industry acceptance of the solution.

Use CMake. CMake is nice. CMake is your friend.

**Comment by andreas23** [comment]
I actually made the build progress by removing the "-j 4" from the everest script. Sorry for the rant. Point still stands, though.

**Comment by msprotz** [comment]
@BarryBo has performed an extensive review of build solutions, and scons seemed like the best option at the time. As far as I know, none of us has had the concurrency issue. Barry, have you managed to install the pywin32 extensions successfully?

**Comment by Chris-Hawblitzel** [comment]
I hadn't seen the file locking error before.  I've been building mostly on Windows (albeit not cygwin) in parallel without pywin32.  If there are errors in the build we should try to reproduce them and fix them.  Is there a good way to reproduce this issue?

In terms of build systems, if I recall correctly the points in favor of SCons were that: (1) it used a fairly standard programming language (Python) for scripting, and (2) it used hashes instead of timestamps.  Our use of it is a fairly recent experiment that arose from frustrations with other build systems.

**Comment by BarryBo** [comment]
The warning in scons about pywin32 relates to a possible crash in the Python .exe when spawning child processes.  It looks like Python27 that we are using, has a non-crashing implementation of os.spawnve() so the warning is bogus.  But nobody seems willing to remove it from Scons.

So the warning does not point to the root cause of your build failure.

One more common source of file locking failures in Windows is antivirus software.  @andreas23, can you do two things for me?

1. Give me specifics of what Windows version you are running, along with the brand and version of antivirus software.
2. Try excluding your C:\Users\bogk\everest directory tree from Antivirus scans, and running a parallel build as before.

**Comment by andreas23** [comment]
This was a Windows 8.1, and the only antivirus running is the built-in Microsoft anti-malware tool.

And of course, trying to reproduce this problem failed, after having updated the sources since them. I was thinking it might be the -NO-VERIFY added recently, but it wasn't . Ah, well.

Is there a way to talk to you guys outside of github issues, btw.? I might be able to allocate research time fot that with my boss.

**Comment by sishtiaq** [comment]
We're actually all github bots :-)
Happy to talk/email instead. I'm on UK-time.

**Comment by BarryBo** [comment]
Thanks for the info.  Nothing we changed in the Scons scripts would change how the .tmp files are produced or consumed.  So it must just be random chance.  If you see another repro, please reach out to me and I'll see what I can do.

I should be reachable by email... I'm on PST.

**Comment by andreas23** [comment]
I'll keep an eye on it. Closing for now.
