### ISSUE TITLE
Visual Studio 2017 isn't detected by the everest script

### ISSUE THREAD

**Issue by BarryBo** [project-everest/everest#35]
VS2017 does not set any VS*COMMNTOOLS environment variables, so it is going to be harder to detect than just expanding the "if" statement in the Everest script.

If a machine has just VS2017 installed, the Everest script will fail to build Vale, as there is no VS_DIR variable set.  The "check" command doesn't check for this case, either.

I have some code in the F* Scons script, which probes the registry in order to locate a Visual Studio install through Cygwin.  That code might be useful here too.

The workaround is easy enough for now... install VS 2015.

**Comment by msprotz** [comment]
Yes, I can look into the SCons script. I have registry querying already in there: 

https://github.com/FStarLang/FStar/blob/master/src/Makefile#L13

I believe something similar could work to detect the more recent versions of VS2017... but I thought VS2017 did expose a VSCOMMNTOOLS variable, since I wrote support for it in https://github.com/FStarLang/kremlin/blob/master/misc/cl-wrapper.bat -- probably need to fix that too.

**Comment by sishtiaq** [comment]
VS2017 seems to be have gone no-registry. Instead, VS 2017 onwards seems to expose an API that let's you ask where it is: https://blogs.msdn.microsoft.com/vcblog/2017/03/06/finding-the-visual-c-compiler-tools-in-visual-studio-2017/. Two implementations of the API are the https://github.com/Microsoft/vswhere script and the https://blogs.msdn.microsoft.com/heaths/2017/01/25/visual-studio-setup-powershell-module-available/ PowerShell module.

**Comment by msprotz** [comment]
Ok... looks like I need a checked-in binary of vswhere.exe in kremlin, then, and a modification to the .bat script in there.

**Comment by tahina-pro** [comment]
I think I fixed that as part of the Docker Windows image (ewerest), based on VS2017. See for instance 8b4ad093077e69173bdd1269825986ea06d9d9d6
