### ISSUE TITLE
Hashes vs submodules

### ISSUE THREAD

**Issue by wintersteiger** [project-everest/everest#59]
Should we consider replacing hashes.sh with git submodules? They have exactly the same purpose as far as I can tell.

@protz @gugavaro @tahina-pro @BarryBo

**Comment by msprotz** [comment]
They used to be submodules but then we backtracked and went into the hashes.sh solution

The reasons weren't documented but as far as I remember:
- people were always inadvertently committing old revisions of git submodules because they forgot to hit "git submodule update"
- difference in the treatment of the .git subdirectory
- no ability to capture the branch, only revisions

the latter is what matter for the everest upgrade, with submodules, we wouldn't have the ability to do that; also, hashes.sh enables a variety of checks (make sure you've pushed your commits, that your branch is in sync) which I believe would be harder to achieve with just submodules

**Comment by wintersteiger** [comment]
Thanks for explaining, makes sense!

(The no-branches restriction doesn't apply to recent gits anymore.)
